# Generated by Django 5.0.3 on 2024-03-17 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('danceability', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('energy', models.DecimalField(decimal_places=10, max_digits=11, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('key', models.PositiveIntegerField()),
                ('loudness', models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MaxValueValidator(0)])),
                ('mode', models.BooleanField()),
                ('acousticness', models.DecimalField(decimal_places=10, max_digits=11, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('instrumentalness', models.DecimalField(decimal_places=10, max_digits=11, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('liveness', models.DecimalField(decimal_places=10, max_digits=11, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('valence', models.DecimalField(decimal_places=10, max_digits=11, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('tempo', models.DecimalField(decimal_places=3, max_digits=6)),
                ('duration_ms', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('time_signature', models.PositiveIntegerField(default=4)),
                ('num_bars', models.PositiveIntegerField()),
                ('num_sections', models.PositiveIntegerField()),
                ('num_segments', models.PositiveIntegerField()),
                ('class_field', models.PositiveIntegerField(default=1)),
                ('rating', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
            ],
        ),
    ]
